import { BonusTile, BonusTileColor, BonusTileType } from "./bonus-tile";
import { DragonType } from "./dragon-type";
import { HonourTile, HonourTileType } from "./honour-tile";
import { SuitedTile, SuitedTileType } from "./suited-tile";
import { Tile } from "./tile";
import { TileType } from "./tile-type";
import { WindType } from "./wind-type";

/**
 * All supported tiles in the game. This is used to generate the wall.
 */
export const TileSet : Tile[] = [
    {id: '1b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 1} as SuitedTile,
    {id: '1b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 1} as SuitedTile,
    {id: '1b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 1} as SuitedTile,
    {id: '1b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 1} as SuitedTile,
    {id: '2b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 2} as SuitedTile,
    {id: '2b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 2} as SuitedTile,
    {id: '2b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 2} as SuitedTile,
    {id: '2b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 2} as SuitedTile,
    {id: '3b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 3} as SuitedTile,
    {id: '3b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 3} as SuitedTile,
    {id: '3b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 3} as SuitedTile,
    {id: '3b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 3} as SuitedTile,
    {id: '4b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 4} as SuitedTile,
    {id: '4b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 4} as SuitedTile,
    {id: '4b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 4} as SuitedTile,
    {id: '4b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 4} as SuitedTile,
    {id: '5b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 5} as SuitedTile,
    {id: '5b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 5} as SuitedTile,
    {id: '5b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 5} as SuitedTile,
    {id: '5b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 5} as SuitedTile,
    {id: '6b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 6} as SuitedTile,
    {id: '6b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 6} as SuitedTile,
    {id: '6b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 6} as SuitedTile,
    {id: '6b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 6} as SuitedTile,
    {id: '7b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 7} as SuitedTile,
    {id: '7b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 7} as SuitedTile,
    {id: '7b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 7} as SuitedTile,
    {id: '7b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 7} as SuitedTile,
    {id: '8b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 8} as SuitedTile,
    {id: '8b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 8} as SuitedTile,
    {id: '8b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 8} as SuitedTile,
    {id: '8b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 8} as SuitedTile,
    {id: '9b-1', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 9} as SuitedTile,
    {id: '9b-2', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 9} as SuitedTile,
    {id: '9b-3', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 9} as SuitedTile,
    {id: '9b-4', type: TileType.SUITED, suite: SuitedTileType.BAMBOO, number: 9} as SuitedTile,
    {id: '1c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 1} as SuitedTile,
    {id: '1c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 1} as SuitedTile,
    {id: '1c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 1} as SuitedTile,
    {id: '1c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 1} as SuitedTile,
    {id: '2c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 2} as SuitedTile,
    {id: '2c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 2} as SuitedTile,
    {id: '2c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 2} as SuitedTile,
    {id: '2c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 2} as SuitedTile,
    {id: '3c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 3} as SuitedTile,
    {id: '3c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 3} as SuitedTile,
    {id: '3c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 3} as SuitedTile,
    {id: '3c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 3} as SuitedTile,
    {id: '4c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 4} as SuitedTile,
    {id: '4c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 4} as SuitedTile,
    {id: '4c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 4} as SuitedTile,
    {id: '4c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 4} as SuitedTile,
    {id: '5c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 5} as SuitedTile,
    {id: '5c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 5} as SuitedTile,
    {id: '5c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 5} as SuitedTile,
    {id: '5c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 5} as SuitedTile,
    {id: '6c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 6} as SuitedTile,
    {id: '6c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 6} as SuitedTile,
    {id: '6c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 6} as SuitedTile,
    {id: '6c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 6} as SuitedTile,
    {id: '7c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 7} as SuitedTile,
    {id: '7c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 7} as SuitedTile,
    {id: '7c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 7} as SuitedTile,
    {id: '7c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 7} as SuitedTile,
    {id: '8c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 8} as SuitedTile,
    {id: '8c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 8} as SuitedTile,
    {id: '8c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 8} as SuitedTile,
    {id: '8c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 8} as SuitedTile,
    {id: '9c-1', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 9} as SuitedTile,
    {id: '9c-2', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 9} as SuitedTile,
    {id: '9c-3', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 9} as SuitedTile,
    {id: '9c-4', type: TileType.SUITED, suite: SuitedTileType.CHARACTER, number: 9} as SuitedTile,
    {id: '1d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 1} as SuitedTile,
    {id: '1d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 1} as SuitedTile,
    {id: '1d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 1} as SuitedTile,
    {id: '1d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 1} as SuitedTile,
    {id: '2d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 2} as SuitedTile,
    {id: '2d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 2} as SuitedTile,
    {id: '2d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 2} as SuitedTile,
    {id: '2d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 2} as SuitedTile,
    {id: '3d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 3} as SuitedTile,
    {id: '3d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 3} as SuitedTile,
    {id: '3d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 3} as SuitedTile,
    {id: '3d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 3} as SuitedTile,
    {id: '4d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 4} as SuitedTile,
    {id: '4d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 4} as SuitedTile,
    {id: '4d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 4} as SuitedTile,
    {id: '4d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 4} as SuitedTile,
    {id: '5d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 5} as SuitedTile,
    {id: '5d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 5} as SuitedTile,
    {id: '5d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 5} as SuitedTile,
    {id: '5d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 5} as SuitedTile,
    {id: '6d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 6} as SuitedTile,
    {id: '6d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 6} as SuitedTile,
    {id: '6d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 6} as SuitedTile,
    {id: '6d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 6} as SuitedTile,
    {id: '7d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 7} as SuitedTile,
    {id: '7d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 7} as SuitedTile,
    {id: '7d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 7} as SuitedTile,
    {id: '7d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 7} as SuitedTile,
    {id: '8d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 8} as SuitedTile,
    {id: '8d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 8} as SuitedTile,
    {id: '8d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 8} as SuitedTile,
    {id: '8d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 8} as SuitedTile,
    {id: '9d-1', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 9} as SuitedTile,
    {id: '9d-2', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 9} as SuitedTile,
    {id: '9d-3', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 9} as SuitedTile,
    {id: '9d-4', type: TileType.SUITED, suite: SuitedTileType.DOTS, number: 9} as SuitedTile,
    {id: 'rd-1', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.RED} as HonourTile,
    {id: 'rd-2', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.RED} as HonourTile,
    {id: 'rd-3', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.RED} as HonourTile,
    {id: 'rd-4', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.RED} as HonourTile,
    {id: 'gd-1', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.GREEN} as HonourTile,
    {id: 'gd-2', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.GREEN} as HonourTile,
    {id: 'gd-3', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.GREEN} as HonourTile,
    {id: 'gd-4', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.GREEN} as HonourTile,
    {id: 'wd-1', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.WHITE} as HonourTile,
    {id: 'wd-2', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.WHITE} as HonourTile,
    {id: 'wd-3', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.WHITE} as HonourTile,
    {id: 'wd-4', type: TileType.HONOUR, honour: HonourTileType.DRAGON, value: DragonType.WHITE} as HonourTile,
    {id: 'ew-1', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.EAST} as HonourTile,
    {id: 'ew-2', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.EAST} as HonourTile,
    {id: 'ew-3', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.EAST} as HonourTile,
    {id: 'ew-4', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.EAST} as HonourTile,
    {id: 'sw-1', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.SOUTH} as HonourTile,
    {id: 'sw-2', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.SOUTH} as HonourTile,
    {id: 'sw-3', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.SOUTH} as HonourTile,
    {id: 'sw-4', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.SOUTH} as HonourTile,
    {id: 'ww-1', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.WEST} as HonourTile,
    {id: 'ww-2', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.WEST} as HonourTile,
    {id: 'ww-3', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.WEST} as HonourTile,
    {id: 'ww-4', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.WEST} as HonourTile,
    {id: 'nw-1', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.NORTH} as HonourTile,
    {id: 'nw-2', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.NORTH} as HonourTile,
    {id: 'nw-3', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.NORTH} as HonourTile,
    {id: 'nw-4', type: TileType.HONOUR, honour: HonourTileType.WIND, value: WindType.NORTH} as HonourTile,
    {id: 'fb-1', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    {id: 'fb-2', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    {id: 'fb-3', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    {id: 'fb-4', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    {id: 'fr-1', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.RED, number: 1} as BonusTile,
    {id: 'fr-2', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.RED, number: 1} as BonusTile,
    {id: 'fr-3', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.RED, number: 1} as BonusTile,
    {id: 'fr-4', type: TileType.BONUS, bonus: BonusTileType.FLOWER, color: BonusTileColor.RED, number: 1} as BonusTile,
    // {id: 'sb-1', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    // {id: 'sb-2', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    // {id: 'sb-3', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    // {id: 'sb-4', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.BLACK, number: 1} as BonusTile,
    // {id: 'sr-1', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.RED, number: 1} as BonusTile,
    // {id: 'sr-2', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.RED, number: 1} as BonusTile,
    // {id: 'sr-3', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.RED, number: 1} as BonusTile,
    // {id: 'sr-4', type: TileType.BONUS, bonus: BonusTileType.SEASON, color: BonusTileColor.RED, number: 1} as BonusTile,
    
] 